### ISSUE TITLE
Vamos a echarlo a andar!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/m3-evaluacion-intermedia-clarabrigido#1]
Vamos al lío, @clarabrigido  !

Algunas pistas para acabarlo:

- [x] Como sugerencia general, comprueba continuamente tu aplicación en Chrome y el terminal dónde arrancas la app con `npm start`. Si algo falla, hay que arreglarlo antes de continuar.
- [x] En el componente del listado hay que recorrer el array de pokemons que le llega por props y pintar una tarjeta por cada uno.
- [x] Termina de añadir los componentes finales: recuerda que **PokeList** suele contener la lista de elementos y **Pokemon** tendrá solo la tarjeta
- [x] Vigila en todo momento los nombres de tus componentes y no llames a un componente dentro de si mismo
- [x] Termina de añadir los elementos finales de la tarjeta de cada Pokemon: un div o article que la englobe (mira el error que tienes en consola) y una imagen para mostrar el Pokemon
- [x] No puedes dejar props con `{}` vacías.
- [x] Cierra correctamente todos tus elementos de jsx
- [x] Revisa en el inspector el código generado siempre.
- [x] Utiliza el nombre del Pokemon para el Alt de la imagen
- [x] Añade un título a la página (Mi lista de Pokemons)
- [x] Usa el `id` de cada pokemon para el  `key` de react cuando mapeas y creas un listado de componentes
- [x] Añade estilos (un archivo sass o css por componente)
- [x] Usa propTypes para comprobar el tipo de dato de las props
- [x] Revisa los metadatos en index.html (lang, title...)
- [x] Limpia e indenta el código
- [x] Publica en Github Pages
- [x] Elimina archivos sin usar y sus referencias

Cuando tengas esto puedes:

1. Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App.
1. Pasar este dato al componente Pokemon por props
1. Pintar Pokemon con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Si tienes cualquier duda, avisa!

Al turrón

**Comment by clarabrigido** [comment]
Hola Carlos!

Está listo. Solamente sale el error que hablamos el otro día del favicon, pero lo he dejado como me dijiste. 
Estoy trabajando en los extras. 

No dudes en comentarme cualquier cosa. 

Gracias,

Clara

**Comment by oneeyedman** [comment]
Buen trabajo, Clara.
